name: Build & Deploy React App

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm i -g npm@11.6.2
      - run: npm --version

      - run: npm install
        working-directory: .
      - run: npm run build
        working-directory: .

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm i -g npm@11.6.2
      - run: npm --version

      - run: npm install
        working-directory: .
      - run: npm run build
        working-directory: .

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages        # branch to deploy to
          folder: dist            # output folder ('dist' for Vite, 'build' for CRA)
